<PROGRAM2>
<CODE_BLOCK2>
<LINE>
<STATEMENT2>
<VARIABLE_INITIATION>
float i;
<END>
<CODE_BLOCK2>
<LINE>
<STATEMENT3>
<FUNCTION_CALL>
<PARAMETER_SETTING_STATEMENT>
<LAST_PARAMETER_SETTING>
<EXPRESSION2>
<OBJECT_DEFINITION>
<FUNCTION_CALL2>
<ARRAY_IMMEDIATE_DEFINITION>
aFunction(new anObject()[1900]);
<END>
