<PROGRAM2>
<CODE_BLOCK2>
<LINE>
<STATEMENT>
<VARIABLE_DEFINITION2>
<EXPRESSION3>
<EQUATION>
<SUB_EXPRESSION2>
<SUB_EXPRESSION3>
i = 100-2.53;
<END>
<CODE_BLOCK2>
<LINE>
<STATEMENT>
<SUB_VARIABLE_IDENTIFIER>
<POSSIBLE_OBJECT>
<POSSIBLE_OBJECT2>
<FUNCTION_CALL2>
<EXPRESSION>
<SUB_EXPRESSION4>
anObject.aFuncObject() = "a literal string";
<END>
